export const SHEETS_ENROLLMENT_COLUMNS: string[] = [
  'Email - (Obrigatoriamente Gmail)',
  'Local que pretende fazer o curso',
  'Horario que pretende fazer o curso',
  'Nome completo',
  'CPF',
  'RG',
  'Orgao Expedidor (Nao colocar CNH)',
  'Data de Nascimento',
  'Natural (UF)',
  'Nome da Mae',
  'Nome do Pai',
  'Endereco',
  'Numero',
  'Bairro',
  'Cidade',
  'Estado',
  'Telefone Pessoal',
  'Telefone Emergencial',
  'Sexo',
  'Escolaridade',
  'Cursou ou cursa a modalidade',
  'Possui deficiencia',
  'Deficiencia / Transtorno',
  'RACA/COR',
  'Inserir todos os documentos em um unico arquivo PDF, seguindo a ordem. RG, CPF,',
]

